apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.server.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.server.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.server.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.server.service.internalPort }}
        resources:
{{ toYaml .Values.server.resources | indent 12 }}
